### PR TITLE
NPM Support

### PR DESCRIPTION
**Pull request by alexkendall**
The following PR adds npm support to the application, updates the readme, and fixes compile errors for both Android & iOS. In the future, an example will be added that does not require any additional dependencies, but the idea here was to make the framework as light-weight as possible.

### CODE REVIEW

**Comment by Jasbir23** [comment]
Hey Alex,
I hope you are doing good :)
Thanks again for everything!! We are using the library extensively for our
project.
I wanted your opinion on something if you dont mind. We have a new
requirement where we have to bridge Google's Cardboard VR library in react
native.
How difficult do you think the task would be?
Please let me know your thoughts on this.

Thanks,
Jasbir

**Comment by alexkendall** [comment]
Hey Jasbir,

Glad to hear that you've found use this library helpful! Im not quite sure how difficult it would be to bridge Google Cardboard's library to react-native but my guess is it wouldn't be too difficult assuming the library isn't enormous. 

Thanks,
Alex

**Comment by Jasbir23** [comment]
Hey Alex,

Hope you are doing good.
 Having some trouble with your library. The Ios code is not working. I
completed all the manual installation steps for ios and android both. The
android code works fine. I get this error with Xcode. Im sending a
screenshot. Please have a look.

Thanks :)
Jasbir

**Comment by Jasbir23** [comment]
Also this

**Pull request merged**
